// Code generated for clava1096 service
// © ant1soc1al.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/clava1096/rocket-service/inventory/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewInventoryService creates a new instance of InventoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInventoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *InventoryService {
	mock := &InventoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// InventoryService is an autogenerated mock type for the InventoryService type
type InventoryService struct {
	mock.Mock
}

type InventoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *InventoryService) EXPECT() *InventoryService_Expecter {
	return &InventoryService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type InventoryService
func (_mock *InventoryService) Get(ctx context.Context, uuid string) (model.Part, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Part, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Part); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Part)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type InventoryService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *InventoryService_Expecter) Get(ctx interface{}, uuid interface{}) *InventoryService_Get_Call {
	return &InventoryService_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *InventoryService_Get_Call) Run(run func(ctx context.Context, uuid string)) *InventoryService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryService_Get_Call) Return(part model.Part, err error) *InventoryService_Get_Call {
	_c.Call.Return(part, err)
	return _c
}

func (_c *InventoryService_Get_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model.Part, error)) *InventoryService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type InventoryService
func (_mock *InventoryService) List(ctx context.Context, filter model.PartsFilter) ([]model.Part, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Part
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) ([]model.Part, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.PartsFilter) []model.Part); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Part)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.PartsFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// InventoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type InventoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.PartsFilter
func (_e *InventoryService_Expecter) List(ctx interface{}, filter interface{}) *InventoryService_List_Call {
	return &InventoryService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *InventoryService_List_Call) Run(run func(ctx context.Context, filter model.PartsFilter)) *InventoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.PartsFilter
		if args[1] != nil {
			arg1 = args[1].(model.PartsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *InventoryService_List_Call) Return(parts []model.Part, err error) *InventoryService_List_Call {
	_c.Call.Return(parts, err)
	return _c
}

func (_c *InventoryService_List_Call) RunAndReturn(run func(ctx context.Context, filter model.PartsFilter) ([]model.Part, error)) *InventoryService_List_Call {
	_c.Call.Return(run)
	return _c
}
