// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: user/v1/user.proto

package userv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest содержит данные для регистрации нового пользователя.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Логин пользователя (уникальный идентификатор для входа).
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Пароль пользователя (будет захеширован на сервере).
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Email пользователя.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Список каналов для уведомлений (telegram, email и т.д.).
	NotificationMethods []*NotificationMethod `protobuf:"bytes,4,rep,name=notification_methods,json=notificationMethods,proto3" json:"notification_methods,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetNotificationMethods() []*NotificationMethod {
	if x != nil {
		return x.NotificationMethods
	}
	return nil
}

// RegisterResponse содержит UUID созданного пользователя.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID зарегистрированного пользователя.
	UserUuid      string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// LoginRequest содержит учетные данные для входа.
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Логин пользователя.
	Login string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	// Пароль пользователя.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse содержит идентификатор созданной сессии.
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID сессии, который нужно передавать в metadata последующих запросов.
	SessionUuid   string `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

// WhoamiRequest содержит идентификатор сессии для проверки авторизации.
type WhoamiRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID активной сессии.
	SessionUuid   string `protobuf:"bytes,1,opt,name=session_uuid,json=sessionUuid,proto3" json:"session_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiRequest) Reset() {
	*x = WhoamiRequest{}
	mi := &file_user_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiRequest) ProtoMessage() {}

func (x *WhoamiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiRequest.ProtoReflect.Descriptor instead.
func (*WhoamiRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *WhoamiRequest) GetSessionUuid() string {
	if x != nil {
		return x.SessionUuid
	}
	return ""
}

// WhoamiResponse содержит базовую информацию о пользователе.
type WhoamiResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID пользователя.
	UserUuid string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// Логин пользователя.
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	// Email пользователя.
	Email         string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiResponse) Reset() {
	*x = WhoamiResponse{}
	mi := &file_user_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiResponse) ProtoMessage() {}

func (x *WhoamiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiResponse.ProtoReflect.Descriptor instead.
func (*WhoamiResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *WhoamiResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *WhoamiResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *WhoamiResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// GetUserRequest содержит UUID пользователя для получения данных.
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID пользователя.
	UserUuid      string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

// GetUserResponse содержит полную информацию о пользователе.
type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID пользователя.
	UserUuid string `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	// Логин пользователя.
	Login string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	// Email пользователя.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// Список настроенных каналов уведомлений.
	NotificationMethods []*NotificationMethod `protobuf:"bytes,4,rep,name=notification_methods,json=notificationMethods,proto3" json:"notification_methods,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserResponse) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetUserResponse) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetNotificationMethods() []*NotificationMethod {
	if x != nil {
		return x.NotificationMethods
	}
	return nil
}

// NotificationMethod описывает способ отправки уведомлений пользователю.
type NotificationMethod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя провайдера (например, "telegram", "email", "push").
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"` // Исправлено на snake_case
	// Адрес получателя (email, chat_id, device_token).
	Target        string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationMethod) Reset() {
	*x = NotificationMethod{}
	mi := &file_user_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationMethod) ProtoMessage() {}

func (x *NotificationMethod) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationMethod.ProtoReflect.Descriptor instead.
func (*NotificationMethod) Descriptor() ([]byte, []int) {
	return file_user_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationMethod) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *NotificationMethod) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

var File_user_v1_user_proto protoreflect.FileDescriptor

const file_user_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12user/v1/user.proto\x12\auser.v1\"\xa9\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12N\n" +
	"\x14notification_methods\x18\x04 \x03(\v2\x1b.user.v1.NotificationMethodR\x13notificationMethods\"/\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"2\n" +
	"\rLoginResponse\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\"2\n" +
	"\rWhoamiRequest\x12!\n" +
	"\fsession_uuid\x18\x01 \x01(\tR\vsessionUuid\"Y\n" +
	"\x0eWhoamiResponse\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"-\n" +
	"\x0eGetUserRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\"\xaa\x01\n" +
	"\x0fGetUserResponse\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12N\n" +
	"\x14notification_methods\x18\x04 \x03(\v2\x1b.user.v1.NotificationMethodR\x13notificationMethods\"Q\n" +
	"\x12NotificationMethod\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target2\xff\x01\n" +
	"\vUserService\x12?\n" +
	"\bRegister\x12\x18.user.v1.RegisterRequest\x1a\x19.user.v1.RegisterResponse\x126\n" +
	"\x05Login\x12\x15.user.v1.LoginRequest\x1a\x16.user.v1.LoginResponse\x129\n" +
	"\x06Whoami\x12\x16.user.v1.WhoamiRequest\x1a\x17.user.v1.WhoamiResponse\x12<\n" +
	"\aGetUser\x12\x17.user.v1.GetUserRequest\x1a\x18.user.v1.GetUserResponseB\x10Z\x0euser/v1;userv1b\x06proto3"

var (
	file_user_v1_user_proto_rawDescOnce sync.Once
	file_user_v1_user_proto_rawDescData []byte
)

func file_user_v1_user_proto_rawDescGZIP() []byte {
	file_user_v1_user_proto_rawDescOnce.Do(func() {
		file_user_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)))
	})
	return file_user_v1_user_proto_rawDescData
}

var file_user_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_user_v1_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: user.v1.RegisterRequest
	(*RegisterResponse)(nil),   // 1: user.v1.RegisterResponse
	(*LoginRequest)(nil),       // 2: user.v1.LoginRequest
	(*LoginResponse)(nil),      // 3: user.v1.LoginResponse
	(*WhoamiRequest)(nil),      // 4: user.v1.WhoamiRequest
	(*WhoamiResponse)(nil),     // 5: user.v1.WhoamiResponse
	(*GetUserRequest)(nil),     // 6: user.v1.GetUserRequest
	(*GetUserResponse)(nil),    // 7: user.v1.GetUserResponse
	(*NotificationMethod)(nil), // 8: user.v1.NotificationMethod
}
var file_user_v1_user_proto_depIdxs = []int32{
	8, // 0: user.v1.RegisterRequest.notification_methods:type_name -> user.v1.NotificationMethod
	8, // 1: user.v1.GetUserResponse.notification_methods:type_name -> user.v1.NotificationMethod
	0, // 2: user.v1.UserService.Register:input_type -> user.v1.RegisterRequest
	2, // 3: user.v1.UserService.Login:input_type -> user.v1.LoginRequest
	4, // 4: user.v1.UserService.Whoami:input_type -> user.v1.WhoamiRequest
	6, // 5: user.v1.UserService.GetUser:input_type -> user.v1.GetUserRequest
	1, // 6: user.v1.UserService.Register:output_type -> user.v1.RegisterResponse
	3, // 7: user.v1.UserService.Login:output_type -> user.v1.LoginResponse
	5, // 8: user.v1.UserService.Whoami:output_type -> user.v1.WhoamiResponse
	7, // 9: user.v1.UserService.GetUser:output_type -> user.v1.GetUserResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_v1_user_proto_init() }
func file_user_v1_user_proto_init() {
	if File_user_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_user_proto_rawDesc), len(file_user_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_user_proto_goTypes,
		DependencyIndexes: file_user_v1_user_proto_depIdxs,
		MessageInfos:      file_user_v1_user_proto_msgTypes,
	}.Build()
	File_user_v1_user_proto = out.File
	file_user_v1_user_proto_goTypes = nil
	file_user_v1_user_proto_depIdxs = nil
}
