// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements CancelOrder operation.
//
// Отменить заказ.
//
// POST /api/v1/orders/{order_uuid}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r CancelOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOrderRequest implements CreateOrderRequest operation.
//
// Создает новый заказ.
//
// POST /api/v1/orders
func (UnimplementedHandler) CreateOrderRequest(ctx context.Context, req *CreateOrderRequest) (r CreateOrderRequestRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetInfoOrderByUUID implements GetInfoOrderByUUID operation.
//
// Получить информацию о заказе по UUID.
//
// GET /api/v1/orders/{order_uuid}
func (UnimplementedHandler) GetInfoOrderByUUID(ctx context.Context, params GetInfoOrderByUUIDParams) (r GetInfoOrderByUUIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// OrderPayment implements OrderPayment operation.
//
// Оплатить заказ.
//
// POST /api/v1/orders/{order_uuid}/pay
func (UnimplementedHandler) OrderPayment(ctx context.Context, req *PayOrderRequest, params OrderPaymentParams) (r OrderPaymentRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *GenericErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *GenericErrorStatusCode) {
	r = new(GenericErrorStatusCode)
	return r
}
