// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderOperation        OperationName = "CancelOrder"
	CreateOrderRequestOperation OperationName = "CreateOrderRequest"
	GetInfoOrderByUUIDOperation OperationName = "GetInfoOrderByUUID"
	OrderPaymentOperation       OperationName = "OrderPayment"
)
