// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements CancelOrder operation.
	//
	// Отменить заказ.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (CancelOrderRes, error)
	// CreateOrderRequest implements CreateOrderRequest operation.
	//
	// Создает новый заказ.
	//
	// POST /api/v1/orders
	CreateOrderRequest(ctx context.Context, req *CreateOrderRequest) (CreateOrderRequestRes, error)
	// GetInfoOrderByUUID implements GetInfoOrderByUUID operation.
	//
	// Получить информацию о заказе по UUID.
	//
	// GET /api/v1/orders/{order_uuid}
	GetInfoOrderByUUID(ctx context.Context, params GetInfoOrderByUUIDParams) (GetInfoOrderByUUIDRes, error)
	// OrderPayment implements OrderPayment operation.
	//
	// Оплатить заказ.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	OrderPayment(ctx context.Context, req *PayOrderRequest, params OrderPaymentParams) (OrderPaymentRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
