// Code generated by ogen, DO NOT EDIT.
package v1

type CancelOrderRes interface {
	cancelOrderRes()
}

type CreateOrderRequestRes interface {
	createOrderRequestRes()
}

type GetInfoOrderByUUIDRes interface {
	getInfoOrderByUUIDRes()
}

type OrderPaymentRes interface {
	orderPaymentRes()
}
